name: Release Go Binaries

on:
  push:
    tags:
      - 'v*'  # 只有當 tag 是 v 開頭才觸發，例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi

          OUTPUT="myapp${EXT}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $OUTPUT

          # 檔名格式：myapp-v1.0.0-windows-amd64.zip
          ARCHIVE="myapp-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          mkdir $ARCHIVE
          mv $OUTPUT $ARCHIVE/

          if [ "${{ matrix.goos }}" = "linux" ]; then
            tar -czf dist/${ARCHIVE}.tar.gz $ARCHIVE
          else
            zip -r dist/${ARCHIVE}.zip $ARCHIVE
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
